Fix building with --disable-static
Fedora packaging rules require ./configure --disable-static.
However, that ends with:
../src/.libs/liberasurecode.so: undefined reference to `dlopen'

The fix is to add a missing -ldl into flags of test_xor_hd_code.